### PR TITLE
[Anvil] Bug fixing + add debug_traceBlockByNumber RPC 

### LINKED ISSUE #457: Lower ED
runtime settings should be more aligned with the one from Westend

https://github.com/paritytech/foundry-polkadot/blob/65bf28cfe6a5b3b6f36803ec5b74c2ec7eaa89b6/crates/anvil-polkadot/substrate-runtime/src/lib.rs?plain=1#L241-L243

```rust
parameter_types! {
    pub const ExistentialDeposit: Balance = DOLLARS;
}
```
vs  1 CENTS on westend

https://github.com/paritytech/polkadot-sdk/blob/rve/tracing-delegate-fix/polkadot/runtime/westend/constants/src/lib.rs?plain=1#L26

This should help lower the gas cost for contract's creation

### PR DESCRIPTION
**Pull request by re-gius**
This PR closes #457 and partially addresses #456.

- fixing the bug of a [GethTrace typ](https://docs.rs/alloy/latest/alloy/rpc/types/trace/geth/struct.CallFrame.html#structfield.typ)(e) being `'"CALL"'` instead of "CALL"
- adding `debug_traceBlockByNumber` RPC endpoint that relies on the implementation from pallet revive + small changes for Geth (I had to add it to the main anvil too, but it's unimplemented there)
- changing existential deposit in runtime to 10^{-3} DOTs

### CODE REVIEW

File: crates/anvil-polkadot/src/api_server/server.rs [hunk 1]
```diff
@@ -414,6 +414,10 @@ impl ApiServer {
                 .debug_trace_call(request, block_number, geth_tracer_options)
                 .await
                 .to_rpc_result(),
+            EthRequest::DebugTraceBlockByNumber(block_number, geth_tracer_options) => self
```
Comment (iulianbarbu) [inline crates/anvil-polkadot/src/api_server/server.rs]: nit: worth adding a comment that this is not a standard anvil RPC

**Review by iulianbarbu — APPROVED** [review]
