### PR TITLE
[Anvil] Fix impersonation marker collision with storage keys

### LINKED ISSUE #488: storage key differs from ethereum
### Component

Anvil

### Describe the bug

When deploying the contract below on `foundry-polkadot` ,
the storage key for the balance mapping is returned as the raw address key instead of the expected keccak mapping slot.

 On Ethereum Anvil, or revive-dev-node the correct mapping slot is returned.

**Contract**
https://gist.github.com/pgherveou/313a619e90060c04762807a33b1b8b6a

**Expected**
Storage key should be the keccak mapping slot:
```
0xe19426bd04f393a626e177a6eea5eac3e1949485b9adf0a55c51e6ed724fbfd3
```

**Actual (foundry-polkadot)**
Storage key returned is the raw address:
```
0x000000000000000000000000a52abfbcdaf1a01acc354f76e792d53d0a2f169a
```

**Repro Script**
```bash
#!/usr/bin/env bash
set -euo pipefail

RPC_URL="${RPC_URL:-http://127.0.0.1:8545}"

DEV_ADDR="0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac"
DEV_PK="5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133"

TARGET_HOLDER="0xA52abfbCDAF1a01acC354f76e792D53D0a2f169A"

WORKDIR="$(mktemp -d)"
cd "$WORKDIR"

echo "Funding dev account..."
cast rpc --rpc-url "$RPC_URL" anvil_setBalance "$DEV_ADDR" "0x3635C9ADC5DEA00000" 2>/dev/null

echo "Fetching contract source..."
curl -sL https://gist.githubusercontent.com/pgherveou/313a619e90060c04762807a33b1b8b6a/raw \
	-o Balance.sol

echo "Compiling..."
BYTECODE="$(solc --combined-json bin Balance.sol | jq -r '.contracts | to_entries[0].value.bin')"

if [[ -z "$BYTECODE" || "$BYTECODE" == "null" ]]; then
	echo "Failed to extract bytecode" >&2
	exit 1
fi

echo "Deploying..."
CONTRACT="$(cast send --json --rpc-url "$RPC_URL" --private-key "$DEV_PK" --create "0x$BYTECODE" | jq -r '.contractAddress')"

echo "Contract deployed at: $CONTRACT"

echo "Tracing balanceOf..."
cast rpc --rpc-url "$RPC_URL" debug_traceCall \
	"$(jq -nc --arg to "$CONTRACT" --arg data "$(cast calldata 'balanceOf(address)' "$TARGET_HOLDER")" '{to:$to,data:$data}')" \
	latest \
	'{"tracer":"prestateTracer","tracerConfig":{"diffMode":false}}' |
	jq --arg addr "$CONTRACT" '.[$addr].storage'

```

### PR DESCRIPTION
**Pull request by pgherveou**
## Summary

- Use `0xDE` marker instead of `0x00` for impersonated transaction signatures to avoid collision with Solidity mapping key computations for slot 0

## Details

When deploying contracts with balance mappings, the storage key was incorrectly returned as the raw address key (e.g., `0x000000000000000000000000a52abfbcdaf1a01acc354f76e792d53d0a2f169a`) instead of the expected keccak mapping slot (e.g., `0xe19426bd04f393a626e177a6eea5eac3e1949485b9adf0a55c51e6ed724fbfd3`).

This happened because the impersonation marker used `[0; 33]` which collided with Solidity mapping key computations for slot 0 (which also have 32 trailing zero bytes).

The fix uses `0xDE` ("DEfake") as a distinctive marker that won't collide with legitimate EVM data.

Closes #488

### CODE REVIEW

File: crates/anvil-polkadot/src/api_server/revive_conversions.rs [hunk 1]
```diff
@@ -420,7 +420,7 @@ impl From<RevivePrestateTraceInfo> for AccountState {
                 .map(|(k, v)| {
                     (
                         B256::from_slice(k.0.as_slice()),
-                        B256::from_slice(v.unwrap_or_default().0.as_slice()),
+                        B256::from_slice(v.unwrap_or(Bytes(vec![0u8; 32])).0.as_slice()),
```
Comment (iulianbarbu) [inline crates/anvil-polkadot/src/api_server/revive_conversions.rs]: is this really needed?

**Review by iulianbarbu — APPROVED** [review]

File: crates/anvil-polkadot/src/substrate_node/host.rs [hunk 2]
```diff
@@ -26,10 +26,17 @@ use sp_runtime_interface::{
...
+/// Previously we used [0; 33] but this collided with Solidity mapping key computations
+/// for slot 0 (which also have 32 trailing zero bytes).
+pub const IMPERSONATION_MARKER: u8 = 0xDE;
+
 // The host functions in this module expect transactions
 // with fake signatures conforming the format checked in this function.
+// Format: [0; 12] + [20-byte address] + [IMPERSONATION_MARKER; 33]
 pub fn is_impersonated(sig: &[u8]) -> bool {
-    sig[..12] == [0; 12] && sig[32..64] == [0; 32]
+    sig[..12] == [0; 12] && sig[32..].iter().all(|&b| b == IMPERSONATION_MARKER)
```
Comment (re-gius) [inline crates/anvil-polkadot/src/substrate_node/host.rs]:
```suggestion
    sig[..12] == [0; 12] && sig[32..64] == [IMPERSONATION_MARKER; 32]
```

I would still leave the check as it was before, to avoid any logic changing the V byte of the signature to affect this
